-- Archivo SQL para la base de datos Supabase

-- 1. Tabla de Personal (Usuarios)
CREATE TABLE IF NOT EXISTS public."Limpieza_Personal" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre TEXT NOT NULL,
    pin TEXT,
    rol TEXT DEFAULT 'operario'
);

-- 2. Tabla de Tareas Planificadas
CREATE TABLE IF NOT EXISTS public."Limpieza_Tareas_Plan" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    descripcion TEXT,
    frecuencia TEXT,
    fecha_vencimiento TEXT, -- Puede ser o no formato ISO
    asignados TEXT[], -- Array de nombres de operarios asignados (null = todos)
    duracion_estimada_minutos INTEGER, -- Para referenciar duración esperada
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla de Registros (Hoja de Horas y Acciones)
CREATE TABLE IF NOT EXISTS public."Limpieza_Registros" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operario TEXT NOT NULL,
    accion TEXT NOT NULL,
    inicio TIMESTAMPTZ NOT NULL,
    fin TIMESTAMPTZ,
    duracion_minutos INTEGER,
    observacion TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabla de Stock (Insumos)
CREATE TABLE IF NOT EXISTS public."Limpieza_Stock" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    cantidad INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabla de Solicitudes de Insumos (Opcional, para formalizar pedidos)
CREATE TABLE IF NOT EXISTS public."Limpieza_Solicitudes" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operario TEXT NOT NULL,
    solicitud TEXT NOT NULL,
    estado TEXT DEFAULT 'Pendiente', -- Pendiente, Aprovado, Rechazado
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Agregar columnas en caso de que las tablas ya existan pero le falten estas columnas:
ALTER TABLE IF EXISTS public."Limpieza_Personal" ADD COLUMN IF NOT EXISTS rol TEXT DEFAULT 'operario';
ALTER TABLE IF EXISTS public."Limpieza_Tareas_Plan" ADD COLUMN IF NOT EXISTS descripcion TEXT;
ALTER TABLE IF EXISTS public."Limpieza_Tareas_Plan" ADD COLUMN IF NOT EXISTS fecha_vencimiento TEXT;
ALTER TABLE IF EXISTS public."Limpieza_Tareas_Plan" ADD COLUMN IF NOT EXISTS asignados TEXT[];
ALTER TABLE IF EXISTS public."Limpieza_Tareas_Plan" ADD COLUMN IF NOT EXISTS duracion_estimada_minutos INTEGER;
ALTER TABLE IF EXISTS public."Limpieza_Registros" ADD COLUMN IF NOT EXISTS observacion TEXT;
